### ISSUE TITLE
Not compatible with 2022.3

### ISSUE THREAD

**Issue by edclement** [bucherfa/accessibility-linter#2]
Using Webstorm 2022.3 and is not compatible. Thanks for your work on this plugin.

**Comment by Finulin** [comment]
Please support 2022.3, we need your good work

**Comment by bucherfa** [comment]
good news: a [new compatible plugin version](https://github.com/bucherfa/accessibility-linter/releases/tag/v0.2.3) should be available on the marketplace once JetBrains reviewed the update :)

**Comment by bucherfa** [comment]
live: https://plugins.jetbrains.com/plugin/19498-accessibility-linter/versions/stable/291061
